### ISSUE TITLE
Problem with deserializing byte arrays

### ISSUE THREAD

**Issue by jordansjones** [rogeralsing/Wire#18]
The following is a simple `LINQPad` example serializing / deserializing a byte array using version 0.0.6:

``` csharp
var msg = new byte[] { 1, 2, 3, 4 };
var serializer = new Serializer(new SerializerOptions(versionTolerance : true, preserveObjectReferences : true));

byte[] serialized;
using (var ms = new MemoryStream())
{
    serializer.Serialize(msg, ms);
    serialized = ms.ToArray();
}

byte[] deserialized;
using (var ms = new MemoryStream(serialized))
{
    deserialized = serializer.Deserialize<byte[]>(ms);
}

msg.SequenceEqual(deserialized).Dump("SequenceEqual");
(msg == deserialized).Dump("msg == deserialized");
msg.Equals(deserialized).Dump("msg.Equals(deserialized)");

msg.Dump("msg");
deserialized.Dump("deserialized");
```

Which results in the following:

![capture](https://cloud.githubusercontent.com/assets/632589/13161125/f10e29fc-d658-11e5-9b48-1c155be6d10a.PNG)

**Comment by rogeralsing** [comment]
That is definitely a bug, fixing asap

**Comment by rogeralsing** [comment]
Fixed, will be included in the next release

**Comment by alexvaluyskiy** [comment]
I've tested it on the latest nightly build and bug is still reproduced

**Comment by rogeralsing** [comment]
Wire doesnt have a nightly build...

**Comment by rogeralsing** [comment]
The above code passes the test 
https://github.com/rogeralsing/Wire/blob/master/Wire.Tests/CollectionTests.cs#L156

**Comment by alexvaluyskiy** [comment]
Sorry, I confused with Akka.Serializer.Wire package. 
Maybe it will be a good idea, to release another version (with bytearray and immutable collection fixed) before it will become the part of Akka?
